server:
  addr: ":8800"
  mode: "debug"

mysql:
  dsn: "root:123456@tcp(127.0.0.1:3306)/fun-service?charset=utf8mb4&parseTime=True&loc=Local"
  max_open_conns: 100
  max_idle_conns: 20

log:
  path: "storage/logs/app.log"
  level: "info"