definitions:
  handler.EmojiAddRequest:
    properties:
      name:
        type: string
      tags:
        items:
          type: string
        type: array
      url:
        type: string
    required:
    - name
    - tags
    - url
    type: object
  handler.LoginParams:
    properties:
      code:
        type: string
      password:
        description: 密码
        type: string
      phone:
        type: string
      type:
        description: 登录类型，phone 或 username
        type: string
      username:
        description: 用户名
        type: string
    required:
    - type
    type: object
  handler.SendCodeParams:
    properties:
      phone:
        type: string
    required:
    - phone
    type: object
  handler.UserParams:
    properties:
      birthdate:
        type: string
      code:
        description: 验证码
        type: string
      email:
        type: string
      nickname:
        type: string
      password:
        type: string
      phone:
        type: string
      username:
        type: string
    required:
    - code
    - password
    - phone
    - username
    type: object
host: localhost:8800
info:
  contact: {}
  title: Fun Service API
  version: "1.0"
paths:
  /emoji/add:
    post:
      consumes:
      - application/json
      description: 添加表情
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: Emoji信息
        in: body
        name: emoji
        required: true
        schema:
          $ref: '#/definitions/handler.EmojiAddRequest'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"msg":"添加表情成功","data":Emoji}'
          schema:
            additionalProperties: true
            type: object
        "400":
          description: '{"code":400,"msg":"xxxx"}'
          schema:
            additionalProperties: true
            type: object
      summary: 添加表情
      tags:
      - emoji
  /login:
    post:
      consumes:
      - application/json
      description: 用户登录
      parameters:
      - description: 登录信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handler.LoginParams'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"msg":"登录成功"}'
          schema:
            additionalProperties: true
            type: object
        "400":
          description: '{"code":400,"msg":"xxxxx",token:"xxxx"}'
          schema:
            additionalProperties: true
            type: object
      summary: 用户登录
      tags:
      - global
  /refresh:
    get:
      consumes:
      - application/json
      description: 刷新重置token
      parameters:
      - description: refresh_token
        in: header
        name: refresh_token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"msg":"刷新重置token成功","token":"xxxx"}'
          schema:
            additionalProperties: true
            type: object
        "400":
          description: '{"code":401,"msg":"xxxxx"}'
          schema:
            additionalProperties: true
            type: object
      summary: 刷新重置token
      tags:
      - global
  /register:
    post:
      consumes:
      - application/json
      description: 用户注册
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handler.UserParams'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"msg":"注册成功"}'
          schema:
            additionalProperties: true
            type: object
        "400":
          description: '{"code":400,"msg":"xxxx"}'
          schema:
            additionalProperties: true
            type: object
      summary: 用户注册
      tags:
      - global
  /sendCode:
    post:
      consumes:
      - application/json
      description: 发送注册手机验证码
      parameters:
      - description: 手机号
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handler.SendCodeParams'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"msg":"验证码发送成功"}'
          schema:
            additionalProperties: true
            type: object
        "400":
          description: '{"code":400,"msg":"参数错误"}'
          schema:
            additionalProperties: true
            type: object
      summary: 发送注册手机验证码
      tags:
      - global
  /upload:
    post:
      consumes:
      - multipart/form-data
      description: 文件上传
      parameters:
      - description: 文件
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"msg":"文件上传成功","url":"xxxx"}'
          schema:
            additionalProperties: true
            type: object
        "400":
          description: '{"code":400,"msg":"xxxxx"}'
          schema:
            additionalProperties: true
            type: object
      summary: 文件上传
      tags:
      - global
  /user/info:
    get:
      consumes:
      - application/json
      description: 获取用户信息
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"msg":"获取用户信息成功","data":UserDTO}'
          schema:
            additionalProperties: true
            type: object
        "400":
          description: '{"code":400,"msg":"xxxxx"}'
          schema:
            additionalProperties: true
            type: object
      summary: 获取用户信息
      tags:
      - user
swagger: "2.0"
